### ISSUE TITLE
Error on apt-get update

### ISSUE THREAD

**Issue by GabLeRoux** [gmantaos/monogame-docker#1]
Hey there, just dropping this here, thanks for the nice work btw :)

I just gave this a try and for some reason, I need to run `apt-get update` to then add some more packages. Thing is when running the `apt-get update` once the image is up, I get the following error message:

> W: Conflicting distribution: http://download.mono-project.com/repo/debian stable-stretch/snapshots/5.18.0.225 InRelease (expected stable-stretch/snapshots/5.18.0.225 but got stretch)

So there seem to be something wrong with the sources.

Edit:
Maybe it's normal and the problem is with `rm -rf /var/lib/apt/lists/* ` at the end. I'll try to build my own docker image and install packages directly into the image instead. I'm trying to get `dotnet` command to be available, but I may not be doing things right.

**Comment by gmantaos** [comment]
Hey, thanks for the interest in the image!

Did you try installing what you need anyway? As far as I understand this is a warning and not error, so it [should not cause problems](https://github.com/mono/docker/issues/40).

As far as the `rm -rf /var/lib/apt/lists/*` line goes, this is standard practice for optimizing the size of a Docker image by removing the package lists that `apt-get update` downloads after installing packages in a Dockerfile.

And as for installing `dotnet`, I just tried it on my own inside the image following [these instructions](https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current) and it seems to work fine :)

**Comment by GabLeRoux** [comment]
Concerning the error, it wasn't clear, but I found out I had a firewall that blocked a few requests.

Thanks for the instructions, I managed to do it here:  
https://github.com/GabLeRoux/docker-dotnet-mono-monogame

Mostly inspired from your image btw. And here's an example project using it:  
https://github.com/LeBodro/KlSS/pull/1
